default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  databse: N2

production:
  <<: *default
  database: N2

test:
   <<: *default
   database: N2_test

