default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: n2

production:
  <<: *default
  database: n2

test:
   <<: *default
   database: n2_test

