default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: n2_user
  password: n2_password
  host: localhost

development:
  <<: *default
  database: n2

production:
  <<: *default
  database: n2

test:
   <<: *default
   database: n2_test

